=== romaframework/romaframework/roma-core/src/main/resources/roma.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.romaframework.org/xml/roma" xmlns="http://www.romaframework.org/xml/roma"
	version="3.0" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:include schemaLocation="roma-core.xsd" />
	<xsd:include schemaLocation="roma-flow.xsd" />
	<xsd:include schemaLocation="roma-i18n.xsd" />
	<xsd:include schemaLocation="roma-logging.xsd" />
	<xsd:include schemaLocation="roma-module.xsd" />
	<xsd:include schemaLocation="roma-persistence.xsd" />
	<xsd:include schemaLocation="roma-profiling.xsd" />
	<xsd:include schemaLocation="roma-reporting.xsd" />
	<xsd:include schemaLocation="roma-scripting.xsd" />
	<xsd:include schemaLocation="roma-semantic.xsd" />
	<xsd:include schemaLocation="roma-service.xsd" />
	<xsd:include schemaLocation="roma-serialization.xsd" />
	<xsd:include schemaLocation="roma-view.xsd" />
	<xsd:include schemaLocation="roma-validation.xsd" />
	<xsd:include schemaLocation="roma-security.xsd" />
	<xsd:include schemaLocation="roma-console.xsd" />
	<xsd:element name="class" type="classType" />

	<xsd:complexType name="classType">
		<xsd:sequence>
			<xsd:element name="aspects" maxOccurs="1" minOccurs="0">
				<xsd:complexType>
					<xsd:choice maxOccurs="unbounded">
						<xsd:element name="core" type="aspectClassTypeCore" minOccurs="0" maxOccurs="1" />
						<xsd:element name="logging" type="aspectClassTypeLogging" minOccurs="0" maxOccurs="1" />
						<xsd:element name="module" type="aspectElementTypeModule" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element name="profiling" type="aspectClassTypeProfiling" minOccurs="0" maxOccurs="1" />
						<xsd:element name="reporting" type="aspectClassTypeReporting" minOccurs="0" maxOccurs="1" />
						<xsd:element name="scripting" type="aspectClassTypeScripting" minOccurs="0" maxOccurs="1" />
						<xsd:element name="security" type="aspectClassTypeSecurity" minOccurs="0" maxOccurs="1" />
						<xsd:element name="semantic" type="aspectClassTypeSemantic" minOccurs="0" maxOccurs="1" />
						<xsd:element name="serialization" type="aspectClassTypeSerialization" minOccurs="0" maxOccurs="1" />
						<xsd:element name="service" type="aspectClassTypeService" minOccurs="0" maxOccurs="1" />
						<xsd:element name="view" type="aspectClassTypeView" minOccurs="0" maxOccurs="1" />
						<xsd:element name="console" type="aspectClassTypeConsole" minOccurs="0" maxOccurs="1" />
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="fields" maxOccurs="1" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="1">
						<xsd:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="actions" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="1">
						<xsd:element type="actionType" name="action" maxOccurs="unbounded" minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="events" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="1">
						<xsd:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="extends" type="xsd:string" use="optional" />
		<xsd:attribute name="implements" type="xsd:string" use="optional" />
	</xsd:complexType>
	<xsd:complexType name="fieldType">
		<xsd:sequence>
			<xsd:element name="aspects" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:choice maxOccurs="unbounded">
						<xsd:element name="core" type="aspectFieldTypeCore" minOccurs="0" maxOccurs="1" />
						<xsd:element name="i18n" type="aspectFieldTypeI18n" minOccurs="0" maxOccurs="1" />
						<xsd:element name="logging" type="aspectFieldTypeLogging" minOccurs="0" maxOccurs="1" />
						<xsd:element name="module" type="aspectElementTypeModule" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element name="persistence" type="aspectTypePersistence" minOccurs="0" maxOccurs="1" />
						<xsd:element name="reporting" type="aspectFieldTypeReporting" minOccurs="0" maxOccurs="1" />
						<xsd:element name="semantic" type="aspectFieldTypeSemantic" minOccurs="0" maxOccurs="1" />
						<xsd:element name="security" type="aspectFieldTypeSecurity" minOccurs="0" maxOccurs="1" />
						<xsd:element name="serialization" type="aspectFieldTypeSerialization" minOccurs="0" maxOccurs="1" />
						<xsd:element name="validation" type="aspectFieldTypeValidation" minOccurs="0" maxOccurs="1" />
						<xsd:element name="view" type="aspectFieldTypeView" minOccurs="0" maxOccurs="1" />
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="events" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="1">
						<xsd:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="value" type="xsd:string" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="type" type="xsd:string" use="optional">
			<xsd:annotation>
				<xsd:documentation>Use standard types: string, integer, float, date, short, byte, char or custom types as well
				</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="actionType">
		<xsd:sequence>
			<xsd:element name="parameters" minOccurs="0">
				<xsd:complexType>
					<xsd:sequence minOccurs="0" maxOccurs="unbounded">
						<xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="1" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="aspects" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:choice maxOccurs="unbounded">
						<xsd:element name="flow" type="aspectActionTypeFlow" minOccurs="0" maxOccurs="1" />
						<xsd:element name="logging" type="aspectActionTypeLogging" minOccurs="0" maxOccurs="1" />
						<xsd:element name="module" type="aspectElementTypeModule" minOccurs="0" maxOccurs="unbounded" />
						<xsd:element name="persistence" type="aspectTypePersistence" minOccurs="0" maxOccurs="1" />
						<xsd:element name="profiling" type="aspectActionTypeProfiling" minOccurs="0" maxOccurs="1" />
						<xsd:element name="scripting" type="aspectActionTypeScripting" minOccurs="0" maxOccurs="1" />
						<xsd:element name="security" type="aspectActionTypeSecurity" minOccurs="0" maxOccurs="1" />
						<xsd:element name="validation" type="aspectActionTypeValidation" minOccurs="0" maxOccurs="1" />
						<xsd:element name="view" type="aspectActionTypeView" minOccurs="0" maxOccurs="1" />
						<xsd:element name="console" type="aspectActionTypeConsole" minOccurs="0" maxOccurs="1" />
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="paramType">
		<xsd:sequence>
			<xsd:element name="aspects" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:choice maxOccurs="unbounded">
						<xsd:element name="console" type="aspectParameterTypeConsole" minOccurs="0" maxOccurs="1" />
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="eventType">
		<xsd:sequence>
			<xsd:element name="aspects" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:choice maxOccurs="unbounded">
						<xsd:element name="flow" type="aspectActionTypeFlow" minOccurs="0" maxOccurs="1" />
						<xsd:element name="logging" type="aspectActionTypeLogging" minOccurs="0" maxOccurs="1" />
						<xsd:element name="security" type="aspectActionTypeSecurity" minOccurs="0" maxOccurs="1" />
						<xsd:element name="scripting" type="aspectEventTypeScripting" minOccurs="0" maxOccurs="1" />
					</xsd:choice>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
	</xsd:complexType>
</xsd:schema>

=== romaframework/romaframework/roma-frontend/src/main/java/org/romaframework/frontend/view/domain/activesession/SessionAttributeInfoInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://www.romaframework.org/xml/roma" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:schemaLocation="http://www.romaframework.org/xml/roma http://www.romaframework.org/schema/v3/roma.xsd">
	<aspects>
		<view columns="1" />
	</aspects>
	<fields>
		<field name="name" />
		<field name="type">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="value">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="type" />
	</fields>
</class>

=== romaframework/romaframework/roma-users/src/main/java/org/romaframework/module/users/view/domain/basegroup/BaseGroupFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://www.romaframework.org/xml/roma" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:schemaLocation="http://www.romaframework.org/xml/roma http://www.romaframework.org/schema/v3/roma.xsd">
	<aspects>
		<view columns="2" />
	</aspects>
	<fields>
		<field name="accountList">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="notes">
			<aspects>
				<view render="text"></view>
			</aspects>
		</field>
	</fields>
</class>

=== romaframework/romaframework/roma-frontend/src/main/java/org/romaframework/frontend/domain/searchengine/filter/AbstractBaseFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://www.romaframework.org/xml/roma" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:schemaLocation="http://www.romaframework.org/xml/roma http://www.romaframework.org/schema/v3/roma.xsd">
	<aspects>
		<view>
			<form>
				<area name="main" type="column">
					<area name="fields" type="form" size="2" />
					<area name="actions" type="row" />
				</area>
			</form>
		</view>
	</aspects>
	<fields>
		<field name="name" />
		<field name="entity">
			<aspects>
				<core useRuntimeType="true" expand="true"/>
			</aspects>
		</field>
		<field name="backObject">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="queryStrategy">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="entityClass">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
	</fields>
	<actions>
		<action name="ok" />
		<action name="cancel" />
	</actions>
</class>

=== romaframework/romaframework/roma-frontend/src/org/romaframework/frontend/domain/wizard/FormWizard.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://www.romaframework.org/xml/roma" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:schemaLocation="http://www.romaframework.org/xml/roma http://www.romaframework.org/schema/v3/roma.xsd">
	<aspects>
		<view>
			<form>
				<area name="main" type="grid" size="1" align="top center">
					<area name="content" align="top center" />
					<area name="actions" type="row" align="top center" />
				</area>
			</form>
		</view>
	</aspects>
	<fields>
		<field name="content">
			<aspects>
				<core useRuntimeType="true" />
				<view render="objectembedded" label="" />
				<validation />
			</aspects>
		</field>
		<field name="entity">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
	</fields>
	<actions>
		<action name="cancel" />
		<action name="begin" />
		<action name="back" />
		<action name="next" />
		<action name="finish" />
	</actions>
</class>

=== romaframework/romaframework/roma-frontend/src/org/romaframework/frontend/view/domain/ApplicationConfigurationPanel.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://www.romaframework.org/xml/roma" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:schemaLocation="http://www.romaframework.org/xml/roma http://www.romaframework.org/schema/v3/roma.xsd">
	<aspects>
		<view>
			<form>
				<area type="column">
					<area name="help" />
					<area name="fields" type="form" size="1" />
					<area name="actions" type="row" />
				</area>
			</form>
		</view>
	</aspects>
	<fields>
		<field name="help" />
		<field name="applicationName">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="applicationPackage">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="applicationVersion">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="applicationDevelopment" />
		<field name="status">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="aspectNames">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="moduleNames">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
	</fields>
</class>

=== romaframework/romaframework/roma-users/src/main/java/org/romaframework/module/users/view/domain/baseaccount/BaseAccountInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://www.romaframework.org/xml/roma" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:schemaLocation="http://www.romaframework.org/xml/roma http://www.romaframework.org/schema/v3/roma.xsd">
	<aspects>
		<view>
			<form>
				<area name="main" type="column">
					<area name="fields" type="form" size="3" />
					<area name="bottomPanel" type="row">
						<area name="notes" type="column" />
						<area name="configuration" type="column" />
					</area>
					<area name="groups" />
					<area name="actions" type="row" />
				</area>
			</form>
		</view>
	</aspects>
	<fields>
		<field name="groups">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="name" />
		<field name="profile">
			<aspects>
				<validation required="true" />
			</aspects>
		</field>
		<field name="signedOn">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="lastModified">
			<aspects>
				<view enabled="false" />
			</aspects>
		</field>
		<field name="email">
			<aspects>
				<validation match="^[_a-z0-9-]+(\.?[_a-z0-9-]*)*@?[a-z0-9-]*(\.?[a-z0-9-]*)*$" />
			</aspects>
		</field>
		<field name="changePasswordNextLogin" />
		<field name="status">
			<aspects>
				<view visible="false" />
				<reporting visible="true" />
			</aspects>
		</field>
		<field name="notes">
			<aspects>
				<view render="textarea" />
			</aspects>
		</field>
		<field name="password">
			<aspects>
				<validation required="true" />
				<reporting visible="false" />
			</aspects>
		</field>
		<field name="confirmPassword">
			<aspects>
				<validation required="true" />
				<reporting visible="false" />
			</aspects>
		</field>
		<field name="statuses">
			<aspects>
				<reporting visible="false" />
			</aspects>
		</field>
		<field name="logoutAfterSave">
			<aspects>
				<reporting visible="false" />
			</aspects>
		</field>
		<field name="configuration"></field>
	</fields>
</class>

=== romaframework/romaframework/roma-users/src/main/java/org/romaframework/module/users/view/domain/activitylog/ActivityLogFilter.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns="http://www.romaframework.org/xml/roma" xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
	xsd:schemaLocation="http://www.romaframework.org/xml/roma http://www.romaframework.org/schema/v3/roma.xsd">
	<aspects>
	</aspects>
	<fields>
		<field name="rangeFrom" />
		<field name="rangeTo" />
		<field name="when">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="account">
			<aspects>
				<view enabled="true" />
			</aspects>
		</field>
		<field name="level">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="levels">
			<aspects>
				<view label="$level" render="select" />
			</aspects>
		</field>
		<field name="category">
			<aspects>
				<view visible="false" />
			</aspects>
		</field>
		<field name="categories">
			<aspects>
				<view label="$category" render="select" />
			</aspects>
		</field>
		<field name="notes" />
	</fields>
</class>
